name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/profile-gitblock.svg
            dist/profile-green-animate.svg
            dist/profile-green.svg
            dist/profile-night-green.svg
            dist/profile-night-rainbow.svg
            dist/profile-night-view.svg
            dist/profile-season-animate.svg
            dist/profile-season.svg
            dist/profile-south-season-animate.svg
            dist/profile-south-season.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push github-profile-3d-contibe to the outptu branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: profile-3d
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
